### ISSUE TITLE
TypeInitializationException when auto property type is not string

### ISSUE THREAD

**Issue by alariois** [HeroicSoft/XF.BindableProperty#2]
When defining a string auto property I can do:
```
[Bindable]
public string Name { get; set; } = "John";
```

When I try to create a bindable property with a type anything other than a string 
```
[Bindable]
int Age { get; set; } = 30;
```
I get the following error
```
System.TypeInitializationException: The type initializer for 'TestFody.Views.TestView' threw an exception. ---> System.InvalidProgramException: Invalid IL code in TestFody.Views.TestView:.cctor (): IL_0095: call      0x0a000034
```

To get it to work, I have to type
```
[Bindable(OnCreateValue = nameof(CreateAge))]
public int Age { get; set; }
private static object CreateAge(BindableObject bindable) => 30;
```

It's of course A LOT better than the alternative.
Since PropertyChanged.Fody seems to handle different types automatically, Im guessing it could be done here also.

Awesome package by the way! :)

**Comment by PascalEschbach** [comment]
Good catch!
This should be fixed in v1.2.1.
