### ISSUE TITLE
Fody: An unhandled exception occurred in VS 2019 Version 16.7.1

### ISSUE THREAD

**Issue by alariois** [HeroicSoft/XF.BindableProperty#3]
After updating Visual Studio a strange error message started to show up in my project.

I created a new Xamarin.Forms project to investigate and I found that whenever I implement Xamarin.Forms.BindableObject (or its superclass) , I cannot add any [Bindable] attributes.

```
public class MyClass : BindableObject
{
    [Bindable]
    public float MyProperty { get; set; }
}
```

Detailed error message:
```
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\Alari\.nuget\packages\xf.bindableproperty.fody\1.2.1\build\..\weaver\XF.BindableProperty.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 202
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 109
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
Type:
System.IO.FileNotFoundException
StackTrace:
   at BindableProperty.Weave()
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 174
Source:
XF.BindableProperty.Fody
TargetSite:
Void Weave()
Could not load file or assembly 'System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
Type:
System.IO.FileNotFoundException
	XFBindablePropertyTest		1	

```

**Comment by PascalEschbach** [comment]
The weaver uses tuples at just once place. Normally fody should automatically load the assembly as its included in the .net standard core library. Which brings me to the question, are you running on .net standard or .net framework? In the framework branch its still a external nuget package.

**Comment by alariois** [comment]
I am using .net standard 2.0

**Comment by alariois** [comment]
I also tried installing System.ValueTuple NuGet manually but this did not remove the error

**Comment by ErikSJan** [comment]
I also face the same problem.
My project is using .net standard 2.1.

Here is the detailed stack of the problem:
System.Exception
StackTrace:
   à InnerWeaver.ExecuteWeavers() dans C:\projects\fody\FodyIsolated\InnerWeaver.cs:ligne 202
   à InnerWeaver.Execute() dans C:\projects\fody\FodyIsolated\InnerWeaver.cs:ligne 109
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Impossible de charger le fichier ou l'assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ou une de ses dépendances. Le fichier spécifié est introuvable.
Type:
System.IO.FileNotFoundException
StackTrace:
   à Mono.Cecil.CecilExtensions.HasSameSignature(MethodDefinition method, TypeReference[] signature)
   à Mono.Cecil.CecilExtensions.HasSameSignature(MethodDefinition method, TypeReference returnType, TypeReference[] signature)
   à BindableProperty.<>c__DisplayClass40_0.<ResolveMethod>b__1(MethodDefinition m)
   à System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   à BindableProperty.ResolveMethod(String name, String searchName, TypeReference returnType, TypeReference[] signature)
   à BindableProperty..ctor(PropertyDefinition property)
   à ModuleWeaver.<>c.<CollectProperties>b__4_4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0)
   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à ModuleWeaver.Execute()
   à InnerWeaver.ExecuteWeavers() dans C:\projects\fody\FodyIsolated\InnerWeaver.cs:ligne 174
Source:
XF.BindableProperty.Fody
TargetSite:
Boolean HasSameSignature(Mono.Cecil.MethodDefinition, Mono.Cecil.TypeReference[])

**Comment by PascalEschbach** [comment]
As it seems MSBuild loads differing versions of System.ValueTuple. As such fody cant find the correct version and therefore crashed.
I just pushed a fix in which I removed all usages of tuples. As such it should now work with v.1.3.0.

**Comment by ErikSJan** [comment]
Hi Pascal,

thanks for the quick fix, as far as I can see it's working as expected 👍 
And by the way thanks a lot also for this package!

**Comment by PascalEschbach** [comment]
Perfect! You're welcome!
